.TH "socioville/Classes/Common Views/MasterView/ Directory Reference" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socioville/Classes/Common Views/MasterView/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCardCell\&.h\fP"
.br
.ti -1c
.RI "file \fBCardCell\&.m\fP"
.br
.ti -1c
.RI "file \fBMasterViewController\&.h\fP"
.br
.ti -1c
.RI "file \fBMasterViewController\&.m\fP"
.br
.ti -1c
.RI "file \fBNewsLoader\&.h\fP"
.br
.ti -1c
.RI "file \fBNewsLoader\&.m\fP"
.br
.in -1c
