.TH "socioville/Libraries/Categories/UISearchBar/ Directory Reference" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socioville/Libraries/Categories/UISearchBar/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBUISearchBar+TextColor\&.h\fP"
.br
.ti -1c
.RI "file \fBUISearchBar+TextColor\&.m\fP"
.br
.in -1c
