.TH "socioville/Libraries/CustomTabBar/ Directory Reference" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socioville/Libraries/CustomTabBar/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBaseViewController\&.h\fP"
.br
.ti -1c
.RI "file \fBBaseViewController\&.m\fP"
.br
.ti -1c
.RI "file \fBCustomTabBarViewController\&.h\fP"
.br
.ti -1c
.RI "file \fBCustomTabBarViewController\&.m\fP"
.br
.ti -1c
.RI "file \fBModalViewController\&.h\fP"
.br
.ti -1c
.RI "file \fBModalViewController\&.m\fP"
.br
.in -1c
