.TH "socioville/Libraries/STSegmentedControl/ Directory Reference" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socioville/Libraries/STSegmentedControl/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBSTSegmentedControl\&.h\fP"
.br
.ti -1c
.RI "file \fBSTSegmentedControl\&.m\fP"
.br
.in -1c
