.TH "ADVPopoverProgressBar" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADVPopoverProgressBar \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <ADVPopoverProgressBar\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(id) - \fBinitWithFrame:andProgressBarColor:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "CGFloat \fBprogress\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (id) initWithFrame: (CGRect)frame(\fBADVProgressBarColor\fP)barColor"

.SH "Property Documentation"
.PP 
.SS "- (CGFloat) progress\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
