.TH "socioville/Libraries/CustomTabBar/BaseViewController.h" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socioville/Libraries/CustomTabBar/BaseViewController.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseViewController\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
