.TH "BaseViewController" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <BaseViewController\&.h>\fP
.PP
Inherited by \fBCustomTabBarViewController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(UIViewController *) - \fBviewControllerWithTabTitle:image:\fP"
.br
.ti -1c
.RI "(void) - \fBaddCenterButtonWithOptions:\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (void) addCenterButtonWithOptions: (NSDictionary *)options"

.SS "- (UIViewController *) viewControllerWithTabTitle: (NSString*)title(UIImage*)image"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
