.TH "BWActivity" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BWActivity \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <BWActivity\&.h>\fP
.PP
Inherited by \fBBWActivityComent\fP, and \fBBWActivityNews\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(id) - \fBinitWithLord\fP"
.br
.ti -1c
.RI "(NSString *) - \fBageDescription\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBBWUser\fP * \fBowner\fP"
.br
.ti -1c
.RI "NSDate * \fBdate\fP"
.br
.ti -1c
.RI "NSInteger \fBtype\fP"
.br
.ti -1c
.RI "NSArray * \fBseenBy\fP"
.br
.ti -1c
.RI "NSArray * \fBrelatedUsers\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (NSString *) ageDescription "

.SS "- (id) initWithLord "

.SH "Property Documentation"
.PP 
.SS "- (NSDate*) date\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (\fBBWUser\fP*) owner\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (NSArray*) relatedUsers\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (NSArray*) seenBy\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (NSInteger) type\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
