.TH "BWActivityLoaderViewController" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BWActivityLoaderViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <BWActivityLoaderViewController\&.h>\fP
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "NSArray * \fBactivities\fP"
.br
.ti -1c
.RI "\fBBWActivityLoader\fP * \fBactiLoader\fP"
.br
.ti -1c
.RI "UITapGestureRecognizer * \fBdismissMenuTap\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBBWUser\fP * \fBuser\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "- (\fBBWActivityLoader\fP*) actiLoader\fC [protected]\fP"

.SS "- (NSArray*) activities\fC [protected]\fP"

.SS "- (UITapGestureRecognizer*) dismissMenuTap\fC [protected]\fP"

.SH "Property Documentation"
.PP 
.SS "- (\fBBWUser\fP*) user\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
