.TH "BWActivityLoader" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BWActivityLoader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <BWActivityLoader\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(id) - \fBinitWithUserName:\fP"
.br
.ti -1c
.RI "(NSArray *) - \fBactivitiesPreparedForProfilePage\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "NSArray * \fBrawActivities\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBuserName\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (NSArray *) activitiesPreparedForProfilePage "

.SS "- (id) initWithUserName: (NSString*)name"

.SH "Member Data Documentation"
.PP 
.SS "- (NSArray*) rawActivities\fC [protected]\fP"

.SH "Property Documentation"
.PP 
.SS "- (NSString*) userName\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
