.TH "BWActivityNews" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BWActivityNews \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <BWActivityNews\&.h>\fP
.PP
Inherits \fBBWActivity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(id) - \fBinitWithNewsSysNamePath:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBnewsSysNamePath\fP"
.br
.ti -1c
.RI "NSString * \fBuserDiscription\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (id) initWithNewsSysNamePath: (NSString*)namePath"

.SH "Property Documentation"
.PP 
.SS "- (NSString*) newsSysNamePath\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (NSString*) userDiscription\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
