.TH "BWAgeCalculator" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BWAgeCalculator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <BWAgeCalculator\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "(NSString *) + \fBdescribeDate:\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "+ (NSString *) describeDate: (NSDate*)date"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
