.TH "BWAppDelegate" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BWAppDelegate \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <BWAppDelegate\&.h>\fP
.PP
Inherits \fB<DBSessionDelegate>\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(void) - \fBsaveContext\fP"
.br
.ti -1c
.RI "(NSURL *) - \fBapplicationDocumentsDirectory\fP"
.br
.ti -1c
.RI "(void) - \fBcustomizeGlobalTheme\fP"
.br
.ti -1c
.RI "(void) - \fBcustomizeiPadTheme\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "(\fBBWAppDelegate\fP *) + \fBinstance\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "UIWindow * \fBwindow\fP"
.br
.ti -1c
.RI "NSManagedObjectContext * \fBmanagedObjectContext\fP"
.br
.ti -1c
.RI "NSManagedObjectModel * \fBmanagedObjectModel\fP"
.br
.ti -1c
.RI "NSPersistentStoreCoordinator * \fBpersistentStoreCoordinator\fP"
.br
.ti -1c
.RI "NSString * \fBdbPlayingGround\fP"
.br
.ti -1c
.RI "\fBColorSwitcher\fP * \fBcolorSwitcher\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (NSURL *) applicationDocumentsDirectory "

.SS "- (void) customizeGlobalTheme "

.SS "- (void) customizeiPadTheme "

.SS "+ (\fBBWAppDelegate\fP *) instance "

.SS "- (void) saveContext "

.SH "Property Documentation"
.PP 
.SS "- (\fBColorSwitcher\fP*) colorSwitcher\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (NSString*) dbPlayingGround\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (NSManagedObjectContext *) managedObjectContext\fC [read]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (NSManagedObjectModel *) managedObjectModel\fC [read]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (NSPersistentStoreCoordinator *) persistentStoreCoordinator\fC [read]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (UIWindow*) window\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
