.TH "BWCameraModalViewController" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BWCameraModalViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <BWCameraModalViewController\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(IBAction) - \fBdoneButton:\fP"
.br
.ti -1c
.RI "(IBAction) - \fBcloseButton:\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "UIImage * \fBselectedImage\fP"
.br
.ti -1c
.RI "NSString * \fBnewsName\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IBOutlet UITextField * \fBnameTextField\fP"
.br
.ti -1c
.RI "IBOutlet UIImageView * \fBphotoImageView\fP"
.br
.ti -1c
.RI "IBOutlet UIActivityIndicatorView * \fBlittleWheel\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (IBAction) closeButton: (id)sender"

.SS "- (IBAction) doneButton: (id)sender"

.SH "Member Data Documentation"
.PP 
.SS "- (NSString*) newsName\fC [protected]\fP"

.SS "- (UIImage*) selectedImage\fC [protected]\fP"

.SH "Property Documentation"
.PP 
.SS "- (IBOutlet UIActivityIndicatorView*) littleWheel\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (IBOutlet UITextField*) nameTextField\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (IBOutlet UIImageView*) photoImageView\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
