.TH "socioville/BWCameraModalViewController.m" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socioville/BWCameraModalViewController.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'BWCameraModalViewController\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "category \fBBWCameraModalViewController()\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
