.TH "BWComment" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BWComment \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <BWComment\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(id) - \fBinitWithAuthor:commentString:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBageDescription\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NSDate * \fBcreatedDate\fP"
.br
.ti -1c
.RI "\fBBWUser\fP * \fBauthor\fP"
.br
.ti -1c
.RI "NSString * \fBcommentString\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (NSString *) ageDescription "

.SS "- (id) initWithAuthor: (\fBBWUser\fP*)theAuthor(NSString*)theCommentString"

.SH "Property Documentation"
.PP 
.SS "- (\fBBWUser\fP*) author\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (NSString*) commentString\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (NSDate*) createdDate\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
