.TH "BWLord" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BWLord \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <BWLord\&.h>\fP
.PP
Inherits \fBBWUser\fP, and \fB<DBRestClientDelegate>\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(\fBBWUser\fP *) - \fBmyLordAsAUser\fP"
.br
.ti -1c
.RI "(NSString *) - \fBprofilePicLocalPath\fP"
.br
.ti -1c
.RI "(NSString *) - \fBmyLordInfoSavePath\fP"
.br
.ti -1c
.RI "(void) - \fBselfDestory\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "(\fBBWLord\fP *) + \fBmyLord\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "id \fBdelegate\fP"
.br
.ti -1c
.RI "NSString * \fBdbPlayingGround\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "+ (\fBBWLord\fP *) myLord "

.SS "- (\fBBWUser\fP *) myLordAsAUser "

.SS "- (NSString *) myLordInfoSavePath "

.SS "- (NSString *) profilePicLocalPath "

.PP
Reimplemented from \fBBWUser\fP\&.
.SS "- (void) selfDestory "

.SH "Property Documentation"
.PP 
.SS "- (NSString*) dbPlayingGround\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (id) delegate\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
