.TH "BWMyLordInfoViewController" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BWMyLordInfoViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <BWMyLordInfoViewController\&.h>\fP
.PP
Inherits \fB<BWLordInfoDelegate>\fP, and \fB<WSQFileUploaderDelegate>\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(IBAction) - \fBchoosePicture:\fP"
.br
.ti -1c
.RI "(IBAction) - \fBsave:\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "UIImage * \fBpickedImage\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBBWLord\fP * \fBlord\fP"
.br
.ti -1c
.RI "IBOutlet UIImageView * \fBprofilPic\fP"
.br
.ti -1c
.RI "IBOutlet UILabel * \fBstatusTextLable\fP"
.br
.ti -1c
.RI "IBOutlet UIActivityIndicatorView * \fBlittleWheel\fP"
.br
.ti -1c
.RI "NSString * \fBnavTitle\fP"
.br
.ti -1c
.RI "id \fBdelegate\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (IBAction) choosePicture: (id)sender"

.SS "- (IBAction) save: (id)sender"

.SH "Member Data Documentation"
.PP 
.SS "- (UIImage*) pickedImage\fC [protected]\fP"

.SH "Property Documentation"
.PP 
.SS "- (id) delegate\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (IBOutlet UIActivityIndicatorView*) littleWheel\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (\fBBWLord\fP*) lord\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (NSString*) navTitle\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (IBOutlet UIImageView*) profilPic\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (IBOutlet UILabel*) statusTextLable\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
