.TH "Yini/BWMyLordInfoViewController.h" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Yini/BWMyLordInfoViewController.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <UIKit/UIKit\&.h>\fP
.br
\fC#import 'BWLord\&.h'\fP
.br
\fC#import 'WSQFileUploader\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBWMyLordInfoViewController\fP"
.br
.ti -1c
.RI "protocol \fB<MyLordInfoViewDelegate>\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
