.TH "BWMyLordActivityWriter" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BWMyLordActivityWriter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <BWMyLordActivityWriter\&.h>\fP
.PP
Inherits \fB<WSQFileUploaderDelegate>\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(void) - \fBaddNewActivity:\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "(\fBBWMyLordActivityWriter\fP *) + \fBsharedLordActiWriter\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "NSMutableArray * \fBmyLordActivities\fP"
.br
.ti -1c
.RI "NSMutableArray * \fBloadedActivities\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (void) addNewActivity: (\fBBWActivity\fP*)activity"

.SS "+ (\fBBWMyLordActivityWriter\fP *) sharedLordActiWriter "

.SH "Member Data Documentation"
.PP 
.SS "- (NSMutableArray*) loadedActivities\fC [protected]\fP"

.SS "- (NSMutableArray*) myLordActivities\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
