.TH "Yini/BWMyLordInfoViewController.m" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Yini/BWMyLordInfoViewController.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'BWMyLordInfoViewController\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "category \fBBWMyLordInfoViewController()\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
