.TH "BWPlayingGroundSettingViewController" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BWPlayingGroundSettingViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <BWPlayingGroundSettingViewController\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(IBAction) - \fBdoneButton:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IBOutlet UITextField * \fBtextField\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (IBAction) doneButton: (id)sender"

.SH "Property Documentation"
.PP 
.SS "- (IBOutlet UITextField*) textField\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
