.TH "BWSystemViewController" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BWSystemViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <BWSystemViewController\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(IBAction) - \fBclearCatchButton:\fP"
.br
.ti -1c
.RI "(IBAction) - \fBlogOutButton:\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (IBAction) clearCatchButton: (id)sender"

.SS "- (IBAction) logOutButton: (id)sender"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
