.TH "BWUser" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BWUser \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <BWUser\&.h>\fP
.PP
Inherited by \fBBWLord\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(id) - \fBinitWithName:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBprofilePicPathForName:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBprofilePicLocalPath\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBDBRestClient\fP * \fBclient\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBdisplayName\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (id) initWithName: (NSString*)name"

.SS "- (NSString *) profilePicLocalPath "

.PP
Reimplemented in \fBBWLord\fP\&.
.SS "- (NSString *) profilePicPathForName: (NSString*)displayUserName"

.SH "Member Data Documentation"
.PP 
.SS "- (\fBDBRestClient\fP*) client\fC [protected]\fP"

.SH "Property Documentation"
.PP 
.SS "- (NSString*) displayName\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
