.TH "BWUserActivityNewsCell" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BWUserActivityNewsCell \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <BWUserActivityNewsCell\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(void) - \fBsetNewsActivity:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IBOutlet UIImageView * \fBmainImageView\fP"
.br
.ti -1c
.RI "IBOutlet UILabel * \fBnameLabel\fP"
.br
.ti -1c
.RI "IBOutlet UILabel * \fBnewsNameLabel\fP"
.br
.ti -1c
.RI "IBOutlet UILabel * \fBdateDescription\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (void) setNewsActivity: (\fBBWActivityNews\fP*)activity"

.SH "Property Documentation"
.PP 
.SS "- (IBOutlet UILabel*) dateDescription\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (IBOutlet UIImageView*) mainImageView\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (IBOutlet UILabel*) nameLabel\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (IBOutlet UILabel*) newsNameLabel\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
