.TH "BWUserActivityCommentsCell" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BWUserActivityCommentsCell \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <BWUserActivityCommentsCell\&.h>\fP
.SS "Properties"

.in +1c
.ti -1c
.RI "IBOutlet UIImageView * \fBprofilePicView\fP"
.br
.ti -1c
.RI "IBOutlet UILabel * \fBnameLable\fP"
.br
.ti -1c
.RI "IBOutlet UILabel * \fBcotentsLabel\fP"
.br
.ti -1c
.RI "IBOutlet UILabel * \fBdateDesctiption\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "- (IBOutlet UILabel*) cotentsLabel\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (IBOutlet UILabel*) dateDesctiption\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (IBOutlet UILabel*) nameLable\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (IBOutlet UIImageView*) profilePicView\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
