.TH "socioville/Classes/Common Views/MasterView/CardCell.m" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socioville/Classes/Common Views/MasterView/CardCell.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'CardCell\&.h'\fP
.br
\fC#import 'BWAppDelegate\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
