.TH "CardCell" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CardCell \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <CardCell\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(id) - \fBinitWithNews:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IBOutlet UIImageView * \fBplayImageView\fP"
.br
.ti -1c
.RI "IBOutlet UIButton * \fBcommentButton\fP"
.br
.ti -1c
.RI "IBOutlet UIButton * \fBlikeButton\fP"
.br
.ti -1c
.RI "IBOutlet UILabel * \fBlabel\fP"
.br
.ti -1c
.RI "IBOutlet UIImageView * \fBmajorImage\fP"
.br
.ti -1c
.RI "IBOutlet UIImageView * \fBuserPic\fP"
.br
.ti -1c
.RI "IBOutlet UIActivityIndicatorView * \fBlittleWheel\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (id) initWithNews: (id)news"

.SH "Property Documentation"
.PP 
.SS "- (IBOutlet UIButton*) commentButton\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"

.SS "- (IBOutlet UILabel*) label\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"

.SS "- (IBOutlet UIButton*) likeButton\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"

.SS "- (IBOutlet UIActivityIndicatorView*) littleWheel\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"

.SS "- (IBOutlet UIImageView*) majorImage\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (IBOutlet UIImageView*) playImageView\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"

.SS "- (IBOutlet UIImageView*) userPic\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
