.TH "ColorChoiceController" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColorChoiceController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <ColorChoiceController\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(UIImage *) - \fBmodifyImage:WithHue:andSaturation:\fP"
.br
.ti -1c
.RI "(IBAction) - \fBdoneModifying:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IBOutlet UIImageView * \fBimageView\fP"
.br
.ti -1c
.RI "IBOutlet UISlider * \fBhueSlider\fP"
.br
.ti -1c
.RI "IBOutlet UILabel * \fBlblHue\fP"
.br
.ti -1c
.RI "IBOutlet UISlider * \fBsaturationSlider\fP"
.br
.ti -1c
.RI "IBOutlet UILabel * \fBlblSaturation\fP"
.br
.ti -1c
.RI "UIImage * \fBimage\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (IBAction) doneModifying: (id)sender"

.SS "- (UIImage *) modifyImage: (UIImage*)originalImage(float)hue(float)saturation"

.SH "Property Documentation"
.PP 
.SS "- (IBOutlet UISlider*) hueSlider\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"

.SS "- (UIImage*) image\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (IBOutlet UIImageView*) imageView\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"

.SS "- (IBOutlet UILabel*) lblHue\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (IBOutlet UILabel*) lblSaturation\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (IBOutlet UISlider*) saturationSlider\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
