.TH "<CustomSegmentedControlDelegate>" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
<CustomSegmentedControlDelegate> \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <CustomSegmentedControl\&.h>\fP
.PP
Inherited by \fBSampleSegment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(UIButton *) - \fBbuttonFor:atIndex:\fP"
.br
.ti -1c
.RI "(void) - \fBtouchUpInsideSegmentIndex:\fP"
.br
.ti -1c
.RI "(void) - \fBtouchDownAtSegmentIndex:\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (UIButton*) buttonFor: (\fBCustomSegmentedControl\fP *)segmentedControl(NSUInteger)segmentIndex"

.SS "- (void) touchDownAtSegmentIndex: (NSUInteger)segmentIndex\fC [optional]\fP"

.SS "- (void) touchUpInsideSegmentIndex: (NSUInteger)segmentIndex\fC [optional]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
