.TH "CustomSegmentedControl" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CustomSegmentedControl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <CustomSegmentedControl\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(id) - \fBinitWithSegmentCount:dividerImage:tag:delegate:\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "NSObject
.br
< \fBCustomSegmentedControlDelegate\fP > * \fBdelegate\fP"
.br
.ti -1c
.RI "NSMutableArray * \fBbuttons\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (id) initWithSegmentCount: (NSUInteger)segmentCount(UIImage*)dividerImage(NSInteger)objectTag(NSObject <\fBCustomSegmentedControlDelegate\fP>*)customSegmentedControlDelegate"

.SH "Member Data Documentation"
.PP 
.SS "- (NSMutableArray*) buttons\fC [protected]\fP"

.SS "- (NSObject<\fBCustomSegmentedControlDelegate\fP>*) delegate\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
