.TH "CustomSegmentedControl()" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CustomSegmentedControl() \- 
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "NSMutableArray * \fBbuttons\fP"
.br
.ti -1c
.RI "NSMutableArray * \fBdividers\fP"
.br
.ti -1c
.RI "UIImage * \fBdividerImg\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "- (NSMutableArray*) buttons\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (UIImage*) dividerImg\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (NSMutableArray*) dividers\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
