.TH "CustomTabBarViewController" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CustomTabBarViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <CustomTabBarViewController\&.h>\fP
.PP
Inherits \fBBaseViewController\fP\&.
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBProgressBanner\fP * \fBpb\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "BOOL \fBallowLandscape\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Data Documentation"
.PP 
.SS "- (\fBProgressBanner\fP*) pb\fC [protected]\fP"

.SH "Property Documentation"
.PP 
.SS "- (BOOL) allowLandscape\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
