.TH "DBDeltaEntry" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DBDeltaEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <DBDeltaEntry\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(id) - \fBinitWithArray:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBlowercasePath\fP"
.br
.ti -1c
.RI "\fBDBMetadata\fP * \fBmetadata\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (id) initWithArray: (NSArray *)array"

.SH "Property Documentation"
.PP 
.SS "- (NSString *) lowercasePath\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (\fBDBMetadata\fP *) metadata\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
