.TH "DropboxSDK.framework/Headers/DBError.h" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DropboxSDK.framework/Headers/DBError.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDBErrorCode\fP { \fBDBErrorNone\fP =  0, \fBDBErrorGenericError\fP =  1000, \fBDBErrorFileNotFound\fP, \fBDBErrorInsufficientDiskSpace\fP, \fBDBErrorIllegalFileType\fP, \fBDBErrorInvalidResponse\fP }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "NSString * \fBDBErrorDomain\fP"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBDBErrorCode\fP"

.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIDBErrorNone \fP\fP
.TP
\fB\fIDBErrorGenericError \fP\fP
.TP
\fB\fIDBErrorFileNotFound \fP\fP
.TP
\fB\fIDBErrorInsufficientDiskSpace \fP\fP
.TP
\fB\fIDBErrorIllegalFileType \fP\fP
.TP
\fB\fIDBErrorInvalidResponse \fP\fP

.SH "Variable Documentation"
.PP 
.SS "NSString* DBErrorDomain"

.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
