.TH "DropboxSDK.framework/Headers/DBJsonWriter.h" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DropboxSDK.framework/Headers/DBJsonWriter.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <Foundation/Foundation\&.h>\fP
.br
\fC#import 'DBJsonBase\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "protocol \fB<DBJsonWriter>\fP"
.br
.RI "\fIOptions for the writer class\&. \fP"
.ti -1c
.RI "class \fBDBJsonWriter\fP"
.br
.RI "\fIThe JSON writer class\&. \fP"
.ti -1c
.RI "category \fBDBJsonWriter(Private)\fP"
.br
.ti -1c
.RI "category \fBNSObject(SBProxyForJson)\fP"
.br
.RI "\fIAllows generation of JSON for otherwise unsupported classes\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
