.TH "DropboxSDK.framework/Headers/DBJsonBase.h" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DropboxSDK.framework/Headers/DBJsonBase.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <Foundation/Foundation\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDBJsonBase\fP"
.br
.RI "\fICommon base class for parsing & writing\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBEUNSUPPORTED\fP =  1, \fBEPARSENUM\fP, \fBEPARSE\fP, \fBEFRAGMENT\fP, \fBECTRL\fP, \fBEUNICODE\fP, \fBEDEPTH\fP, \fBEESCAPE\fP, \fBETRAILCOMMA\fP, \fBETRAILGARBAGE\fP, \fBEEOF\fP, \fBEINPUT\fP }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "NSString * \fBDBJSONErrorDomain\fP"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIEUNSUPPORTED \fP\fP
.TP
\fB\fIEPARSENUM \fP\fP
.TP
\fB\fIEPARSE \fP\fP
.TP
\fB\fIEFRAGMENT \fP\fP
.TP
\fB\fIECTRL \fP\fP
.TP
\fB\fIEUNICODE \fP\fP
.TP
\fB\fIEDEPTH \fP\fP
.TP
\fB\fIEESCAPE \fP\fP
.TP
\fB\fIETRAILCOMMA \fP\fP
.TP
\fB\fIETRAILGARBAGE \fP\fP
.TP
\fB\fIEEOF \fP\fP
.TP
\fB\fIEINPUT \fP\fP

.SH "Variable Documentation"
.PP 
.SS "NSString* DBJSONErrorDomain"

.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
