.TH "DBMetadata" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DBMetadata \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <DBMetadata\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(id) - \fBinitWithDictionary:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "BOOL \fBthumbnailExists\fP"
.br
.ti -1c
.RI "long long \fBtotalBytes\fP"
.br
.ti -1c
.RI "NSDate * \fBlastModifiedDate\fP"
.br
.ti -1c
.RI "NSDate * \fBclientMtime\fP"
.br
.ti -1c
.RI "NSString * \fBpath\fP"
.br
.ti -1c
.RI "BOOL \fBisDirectory\fP"
.br
.ti -1c
.RI "NSArray * \fBcontents\fP"
.br
.ti -1c
.RI "NSString * \fBhash\fP"
.br
.ti -1c
.RI "NSString * \fBhumanReadableSize\fP"
.br
.ti -1c
.RI "NSString * \fBroot\fP"
.br
.ti -1c
.RI "NSString * \fBicon\fP"
.br
.ti -1c
.RI "long long \fBrevision\fP"
.br
.ti -1c
.RI "NSString * \fBrev\fP"
.br
.ti -1c
.RI "BOOL \fBisDeleted\fP"
.br
.ti -1c
.RI "NSString * \fBfilename\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (id) initWithDictionary: (NSDictionary *)dict"

.SH "Property Documentation"
.PP 
.SS "- (NSDate *) clientMtime\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (NSArray *) contents\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (NSString *) filename\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (NSString *) hash\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (NSString *) humanReadableSize\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (NSString *) icon\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (BOOL) isDeleted\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (BOOL) isDirectory\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (NSDate *) lastModifiedDate\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (NSString *) path\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (NSString *) rev\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (long long) revision\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (NSString *) root\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (BOOL) thumbnailExists\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (long long) totalBytes\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
