.TH "DBQuota" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DBQuota \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <DBQuota\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(id) - \fBinitWithDictionary:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "long long \fBnormalConsumedBytes\fP"
.br
.ti -1c
.RI "long long \fBsharedConsumedBytes\fP"
.br
.ti -1c
.RI "long long \fBtotalConsumedBytes\fP"
.br
.ti -1c
.RI "long long \fBtotalBytes\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (id) initWithDictionary: (NSDictionary *)dict"

.SH "Property Documentation"
.PP 
.SS "- (long long) normalConsumedBytes\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (long long) sharedConsumedBytes\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (long long) totalBytes\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (long long) totalConsumedBytes\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
