.TH "<DBRestClientPhotosDelegate>" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
<DBRestClientPhotosDelegate> \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <DBRestClient+Photos\&.h>\fP
.PP
Inherits \fB<DBRestClientDelegate>\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(void) - \fBrestClient:loadedCuDeltaEntries:reset:cursor:hasMore:\fP"
.br
.ti -1c
.RI "(void) - \fBrestClient:loadCuDeltaFailedWithError:\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (void) restClient: (\fBDBRestClient\fP *)client(NSError *)error"

.SS "- (void) restClient: (\fBDBRestClient\fP *)client(NSArray *)entries(BOOL)shouldReset(NSString *)cursor(BOOL)hasMore"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
