.TH "<DBSessionDelegate>" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
<DBSessionDelegate> \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <DBSession\&.h>\fP
.PP
Inherited by \fBBWAppDelegate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(void) - \fBsessionDidReceiveAuthorizationFailure:userId:\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (void) sessionDidReceiveAuthorizationFailure: (\fBDBSession\fP *)session(NSString *)userId"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
