.TH "DropboxSDK.framework/Headers/DBSession.h" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DropboxSDK.framework/Headers/DBSession.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'MPOAuthCredentialConcreteStore\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDBSession\fP"
.br
.ti -1c
.RI "protocol \fB<DBSessionDelegate>\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "NSString * \fBkDBSDKVersion\fP"
.br
.ti -1c
.RI "NSString * \fBkDBDropboxAPIHost\fP"
.br
.ti -1c
.RI "NSString * \fBkDBDropboxAPIContentHost\fP"
.br
.ti -1c
.RI "NSString * \fBkDBDropboxWebHost\fP"
.br
.ti -1c
.RI "NSString * \fBkDBDropboxAPIVersion\fP"
.br
.ti -1c
.RI "NSString * \fBkDBRootDropbox\fP"
.br
.ti -1c
.RI "NSString * \fBkDBRootAppFolder\fP"
.br
.ti -1c
.RI "NSString * \fBkDBProtocolHTTPS\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "NSString* kDBDropboxAPIContentHost"

.SS "NSString* kDBDropboxAPIHost"

.SS "NSString* kDBDropboxAPIVersion"

.SS "NSString* kDBDropboxWebHost"

.SS "NSString* kDBProtocolHTTPS"

.SS "NSString* kDBRootAppFolder"

.SS "NSString* kDBRootDropbox"

.SS "NSString* kDBSDKVersion"

.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
