.TH "DetailViewController()" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DetailViewController() \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(void) - \fBconfigureView\fP"
.br
.ti -1c
.RI "(void) - \fBshowMovieForURL:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "MPMoviePlayerController * \fBmovieController\fP"
.br
.ti -1c
.RI "UIPopoverController * \fBmasterPopoverController\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (void) configureView "

.SS "- (void) showMovieForURL: (NSURL *)movieURL"

.SH "Property Documentation"
.PP 
.SS "- (UIPopoverController*) masterPopoverController\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (MPMoviePlayerController*) movieController\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
