.TH "DetailViewController" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DetailViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <DetailViewController\&.h>\fP
.PP
Inherits \fB<NewsLoaderDelegate>\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(IBAction) - \fBplayMovie:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "id \fBdetailItem\fP"
.br
.ti -1c
.RI "IBOutlet UIImageView * \fBnewsMediaImageView\fP"
.br
.ti -1c
.RI "IBOutlet UITextField * \fBnewsNameTextField\fP"
.br
.ti -1c
.RI "IBOutlet UIImageView * \fBimageView\fP"
.br
.ti -1c
.RI "IBOutlet UITableView * \fBtableView\fP"
.br
.ti -1c
.RI "IBOutlet UILabel * \fBdetailDescriptionLabel\fP"
.br
.ti -1c
.RI "IBOutlet UIButton * \fBplayButton\fP"
.br
.ti -1c
.RI "IBOutlet UIActivityIndicatorView * \fBlittleWheel\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (IBAction) playMovie: (id)sender"

.SH "Property Documentation"
.PP 
.SS "- (IBOutlet UILabel*) detailDescriptionLabel\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (id) detailItem\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (IBOutlet UIImageView*) imageView\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (IBOutlet UIActivityIndicatorView*) littleWheel\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"

.SS "- (IBOutlet UIImageView*) newsMediaImageView\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (IBOutlet UITextField*) newsNameTextField\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"

.SS "- (IBOutlet UIButton*) playButton\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (IBOutlet UITableView*) tableView\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
