.TH "ListCell" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListCell \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <ListCell\&.h>\fP
.SS "Properties"

.in +1c
.ti -1c
.RI "IBOutlet UILabel * \fBtitleLabel\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "- (IBOutlet UILabel*) titleLabel\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
