.TH "Yini/main.m" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Yini/main.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import <UIKit/UIKit\&.h>\fP
.br
\fC#import 'BWAppDelegate\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
