.TH "MasterViewController" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MasterViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <MasterViewController\&.h>\fP
.PP
Inherits \fBPullRefreshTableViewController\fP, \fB<NewsLoaderDelegate>\fP, \fB<ZUUIRevealControllerDelegate>\fP, and \fB<MyLordInfoViewDelegate>\fP\&.
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "UIActivityIndicatorView * \fBactIndi\fP"
.br
.ti -1c
.RI "\fBNewsLoader\fP * \fBloader\fP"
.br
.ti -1c
.RI "NSArray * \fBdatasource\fP"
.br
.ti -1c
.RI "NSInteger \fBselected\fP"
.br
.ti -1c
.RI "UITapGestureRecognizer * \fBdismissMenuTap\fP"
.br
.ti -1c
.RI "BOOL \fBgotAProfilePic\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Data Documentation"
.PP 
.SS "- (UIActivityIndicatorView*) actIndi\fC [protected]\fP"

.SS "- (NSArray*) datasource\fC [protected]\fP"

.SS "- (UITapGestureRecognizer*) dismissMenuTap\fC [protected]\fP"

.SS "- (BOOL) gotAProfilePic\fC [protected]\fP"

.SS "- (\fBNewsLoader\fP*) loader\fC [protected]\fP"

.SS "- (NSInteger) selected\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
