.TH "socioville/Classes/Common Views/MasterView/MasterViewController.m" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socioville/Classes/Common Views/MasterView/MasterViewController.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'MasterViewController\&.h'\fP
.br
\fC#import 'ZUUIRevealController\&.h'\fP
.br
\fC#import 'DetailViewController\&.h'\fP
.br
\fC#import 'BWAppDelegate\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "category \fBMasterViewController()\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
