.TH "MenuItem" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MenuItem \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <MenuItem\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "(\fBMenuItem\fP *) + \fBitemWithData:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBname\fP"
.br
.ti -1c
.RI "NSString * \fBimageName\fP"
.br
.ti -1c
.RI "UIImage * \fBimage\fP"
.br
.ti -1c
.RI "NSNumber * \fBeventCount\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "+ (\fBMenuItem\fP *) itemWithData: (NSDictionary *)data"

.SH "Property Documentation"
.PP 
.SS "- (NSNumber*) eventCount\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (UIImage*) image\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (NSString*) imageName\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (NSString*) name\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
