.TH "MenuViewController" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MenuViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <MenuViewController\&.h>\fP
.PP
Inherits \fB<ZUUIRevealControllerDelegate>\fP, \fB<WSQFileHelperDelegate>\fP, and \fB<MyLordInfoViewDelegate>\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "IBOutlet UISearchBar * \fBsearchBar\fP"
.br
.ti -1c
.RI "IBOutlet UITableView * \fBtableView\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Property Documentation"
.PP 
.SS "- (IBOutlet UISearchBar*) searchBar\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (IBOutlet UITableView*) tableView\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
