.TH "DropboxSDK.framework/Headers/MPOAuthSignatureParameter.h" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DropboxSDK.framework/Headers/MPOAuthSignatureParameter.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <Foundation/Foundation\&.h>\fP
.br
\fC#import 'MPURLRequestParameter\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMPOAuthSignatureParameter\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBkMPOAuthSignatureMethodPlaintext\fP   @'PLAINTEXT'"
.br
.ti -1c
.RI "#define \fBkMPOAuthSignatureMethodHMACSHA1\fP   @'HMAC-SHA1'"
.br
.ti -1c
.RI "#define \fBkMPOAuthSignatureMethodRSASHA1\fP   @'RSA-SHA1'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define kMPOAuthSignatureMethodHMACSHA1   @'HMAC-SHA1'"

.SS "#define kMPOAuthSignatureMethodPlaintext   @'PLAINTEXT'"

.SS "#define kMPOAuthSignatureMethodRSASHA1   @'RSA-SHA1'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
