.TH "MPOAuthURLResponse" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPOAuthURLResponse \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <MPOAuthURLResponse\&.h>\fP
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "NSURLResponse * \fB_urlResponse\fP"
.br
.ti -1c
.RI "NSDictionary * \fB_oauthParameters\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NSURLResponse * \fBurlResponse\fP"
.br
.ti -1c
.RI "NSDictionary * \fBoauthParameters\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "- (NSDictionary*) _oauthParameters\fC [protected]\fP"

.SS "- (NSURLResponse*) _urlResponse\fC [protected]\fP"

.SH "Property Documentation"
.PP 
.SS "- (NSDictionary*) oauthParameters\fC [read]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"

.SS "- (NSURLResponse*) urlResponse\fC [read]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
