.TH "<MPOAuthParameterFactory>" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
<MPOAuthParameterFactory> \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <MPOAuthParameterFactory\&.h>\fP
.PP
Inherited by \fBMPOAuthCredentialConcreteStore\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(NSArray *) - \fBoauthParameters\fP"
.br
.ti -1c
.RI "(\fBMPURLRequestParameter\fP *) - \fBoauthConsumerKeyParameter\fP"
.br
.ti -1c
.RI "(\fBMPURLRequestParameter\fP *) - \fBoauthTokenParameter\fP"
.br
.ti -1c
.RI "(\fBMPURLRequestParameter\fP *) - \fBoauthSignatureMethodParameter\fP"
.br
.ti -1c
.RI "(\fBMPURLRequestParameter\fP *) - \fBoauthTimestampParameter\fP"
.br
.ti -1c
.RI "(\fBMPURLRequestParameter\fP *) - \fBoauthNonceParameter\fP"
.br
.ti -1c
.RI "(\fBMPURLRequestParameter\fP *) - \fBoauthVersionParameter\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBsignatureMethod\fP"
.br
.ti -1c
.RI "NSString * \fBsigningKey\fP"
.br
.ti -1c
.RI "NSString * \fBtimestamp\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (\fBMPURLRequestParameter\fP *) oauthConsumerKeyParameter "

.SS "- (\fBMPURLRequestParameter\fP *) oauthNonceParameter "

.SS "- (NSArray *) oauthParameters "

.SS "- (\fBMPURLRequestParameter\fP *) oauthSignatureMethodParameter "

.SS "- (\fBMPURLRequestParameter\fP *) oauthTimestampParameter "

.SS "- (\fBMPURLRequestParameter\fP *) oauthTokenParameter "

.SS "- (\fBMPURLRequestParameter\fP *) oauthVersionParameter "

.SH "Property Documentation"
.PP 
.SS "- (NSString*) signatureMethod\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"

.SS "- (NSString*) signingKey\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (NSString*) timestamp\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
