.TH "DropboxSDK.framework/Headers/MPOAuthCredentialStore.h" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DropboxSDK.framework/Headers/MPOAuthCredentialStore.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "protocol \fB<MPOAuthCredentialStore>\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "NSString * \fBkMPOAuthCredentialConsumerKey\fP"
.br
.ti -1c
.RI "NSString * \fBkMPOAuthCredentialConsumerSecret\fP"
.br
.ti -1c
.RI "NSString * \fBkMPOAuthCredentialUsername\fP"
.br
.ti -1c
.RI "NSString * \fBkMPOAuthCredentialPassword\fP"
.br
.ti -1c
.RI "NSString * \fBkMPOAuthCredentialRequestToken\fP"
.br
.ti -1c
.RI "NSString * \fBkMPOAuthCredentialRequestTokenSecret\fP"
.br
.ti -1c
.RI "NSString * \fBkMPOAuthCredentialAccessToken\fP"
.br
.ti -1c
.RI "NSString * \fBkMPOAuthCredentialAccessTokenSecret\fP"
.br
.ti -1c
.RI "NSString * \fBkMPOAuthCredentialSessionHandle\fP"
.br
.ti -1c
.RI "NSString * \fBkMPOAuthCredentialRealm\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "NSString* kMPOAuthCredentialAccessToken"

.SS "NSString* kMPOAuthCredentialAccessTokenSecret"

.SS "NSString* kMPOAuthCredentialConsumerKey"

.SS "NSString* kMPOAuthCredentialConsumerSecret"

.SS "NSString* kMPOAuthCredentialPassword"

.SS "NSString* kMPOAuthCredentialRealm"

.SS "NSString* kMPOAuthCredentialRequestToken"

.SS "NSString* kMPOAuthCredentialRequestTokenSecret"

.SS "NSString* kMPOAuthCredentialSessionHandle"

.SS "NSString* kMPOAuthCredentialUsername"

.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
