.TH "MPOAuthCredentialConcreteStore" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPOAuthCredentialConcreteStore \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <MPOAuthCredentialConcreteStore\&.h>\fP
.PP
Inherits \fB<MPOAuthCredentialStore>\fP, and \fB<MPOAuthParameterFactory>\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(id) - \fBinitWithCredentials:\fP"
.br
.ti -1c
.RI "(id) - \fBinitWithCredentials:forBaseURL:\fP"
.br
.ti -1c
.RI "(id) - \fBinitWithCredentials:forBaseURL:withAuthenticationURL:\fP"
.br
.ti -1c
.RI "(void) - \fBsetCredential:withName:\fP"
.br
.ti -1c
.RI "(void) - \fBremoveCredentialNamed:\fP"
.br
.ti -1c
.RI "(void) - \fBaddToKeychainUsingName:andValue:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBfindValueFromKeychainUsingName:\fP"
.br
.ti -1c
.RI "(void) - \fBremoveValueFromKeychainUsingName:\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "NSMutableDictionary * \fBstore_\fP"
.br
.ti -1c
.RI "NSURL * \fBbaseURL_\fP"
.br
.ti -1c
.RI "NSURL * \fBauthenticationURL_\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NSURL * \fBbaseURL\fP"
.br
.ti -1c
.RI "NSURL * \fBauthenticationURL\fP"
.br
.ti -1c
.RI "NSString * \fBtokenSecret\fP"
.br
.ti -1c
.RI "NSString * \fBsigningKey\fP"
.br
.ti -1c
.RI "NSString * \fBrequestToken\fP"
.br
.ti -1c
.RI "NSString * \fBrequestTokenSecret\fP"
.br
.ti -1c
.RI "NSString * \fBaccessToken\fP"
.br
.ti -1c
.RI "NSString * \fBaccessTokenSecret\fP"
.br
.ti -1c
.RI "NSString * \fBsessionHandle\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (void) addToKeychainUsingName: (NSString *)inName(NSString *)inValue"

.SS "- (NSString *) findValueFromKeychainUsingName: (NSString *)inName"

.SS "- (id) initWithCredentials: (NSDictionary *)inCredential"

.SS "- (id) \fBinitWithCredentials:\fP (NSDictionary *)inCredentials(NSURL *)inBaseURL"

.SS "- (id) \fBinitWithCredentials:\fP (NSDictionary *)inCredentials(NSURL *)inBaseURL(NSURL *)inAuthenticationURL"

.SS "- (void) removeCredentialNamed: (NSString *)inName"

.SS "- (void) removeValueFromKeychainUsingName: (NSString *)inName"

.SS "- (void) setCredential: (id)inCredential(NSString *)inName"

.SH "Member Data Documentation"
.PP 
.SS "- (NSURL*) authenticationURL_\fC [protected]\fP"

.SS "- (NSURL*) baseURL_\fC [protected]\fP"

.SS "- (NSMutableDictionary*) store_\fC [protected]\fP"

.SH "Property Documentation"
.PP 
.SS "- (NSString*) accessToken\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"

.SS "- (NSString*) accessTokenSecret\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"

.SS "- (NSURL*) authenticationURL\fC [read]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"

.SS "- (NSURL*) baseURL\fC [read]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"

.SS "- (NSString*) requestToken\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"

.SS "- (NSString*) requestTokenSecret\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"

.SS "- (NSString*) sessionHandle\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"

.SS "- (NSString*) signingKey\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (NSString*) tokenSecret\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
