.TH "DropboxSDK.framework/Headers/MPOAuthAPIRequestLoader.h" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DropboxSDK.framework/Headers/MPOAuthAPIRequestLoader.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <Foundation/Foundation\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMPOAuthAPIRequestLoader\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "NSString *const \fBMPOAuthNotificationRequestTokenReceived\fP"
.br
.ti -1c
.RI "NSString *const \fBMPOAuthNotificationRequestTokenRejected\fP"
.br
.ti -1c
.RI "NSString *const \fBMPOAuthNotificationAccessTokenReceived\fP"
.br
.ti -1c
.RI "NSString *const \fBMPOAuthNotificationAccessTokenRejected\fP"
.br
.ti -1c
.RI "NSString *const \fBMPOAuthNotificationAccessTokenRefreshed\fP"
.br
.ti -1c
.RI "NSString *const \fBMPOAuthNotificationErrorHasOccurred\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "NSString* const MPOAuthNotificationAccessTokenReceived"

.SS "NSString* const MPOAuthNotificationAccessTokenRefreshed"

.SS "NSString* const MPOAuthNotificationAccessTokenRejected"

.SS "NSString* const MPOAuthNotificationErrorHasOccurred"

.SS "NSString* const MPOAuthNotificationRequestTokenReceived"

.SS "NSString* const MPOAuthNotificationRequestTokenRejected"

.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
