.TH "<MPOAuthCredentialStore>" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
<MPOAuthCredentialStore> \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <MPOAuthCredentialStore\&.h>\fP
.PP
Inherited by \fBMPOAuthCredentialConcreteStore\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(NSString *) - \fBcredentialNamed:\fP"
.br
.ti -1c
.RI "(void) - \fBdiscardOAuthCredentials\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBconsumerKey\fP"
.br
.ti -1c
.RI "NSString * \fBconsumerSecret\fP"
.br
.ti -1c
.RI "NSString * \fBusername\fP"
.br
.ti -1c
.RI "NSString * \fBpassword\fP"
.br
.ti -1c
.RI "NSString * \fBrequestToken\fP"
.br
.ti -1c
.RI "NSString * \fBrequestTokenSecret\fP"
.br
.ti -1c
.RI "NSString * \fBaccessToken\fP"
.br
.ti -1c
.RI "NSString * \fBaccessTokenSecret\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (NSString *) credentialNamed: (NSString *)inCredentialName"

.SS "- (void) discardOAuthCredentials "

.SH "Property Documentation"
.PP 
.SS "- (NSString*) accessToken\fC [read]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"

.SS "- (NSString*) accessTokenSecret\fC [read]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"

.SS "- (NSString*) consumerKey\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (NSString*) consumerSecret\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (NSString*) password\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (NSString*) requestToken\fC [read]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"

.SS "- (NSString*) requestTokenSecret\fC [read]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"

.SS "- (NSString*) username\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
