.TH "<MPOAuthAuthenticationMethodOAuthDelegate>" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
<MPOAuthAuthenticationMethodOAuthDelegate> \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <MPOAuthAuthenticationMethodOAuth\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(NSURL *) - \fBcallbackURLForCompletedUserAuthorization\fP"
.br
.ti -1c
.RI "(BOOL) - \fBautomaticallyRequestAuthenticationFromURL:withCallbackURL:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBoauthVerifierForCompletedUserAuthorization\fP"
.br
.ti -1c
.RI "(void) - \fBauthenticationDidFailWithError:\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (void) authenticationDidFailWithError: (NSError *)error\fC [optional]\fP"

.SS "- (BOOL) automaticallyRequestAuthenticationFromURL: (NSURL *)inAuthURL(NSURL *)inCallbackURL"

.SS "- (NSURL *) callbackURLForCompletedUserAuthorization "

.SS "- (NSString *) oauthVerifierForCompletedUserAuthorization \fC [optional]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
