.TH "<MyLordInfoViewDelegate>" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
<MyLordInfoViewDelegate> \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <BWMyLordInfoViewController\&.h>\fP
.PP
Inherited by \fBMasterViewController\fP, and \fBMenuViewController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(void) - \fBmyLordInfoViewDidGotNewProfile\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (void) myLordInfoViewDidGotNewProfile "


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
