.TH "NewsObjectPhoto" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewsObjectPhoto \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <NewsObjectPhoto\&.h>\fP
.PP
Inherits \fBWSQNews\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(\fBNewsObjectPhoto\fP *) - \fBloadPhoto\fP"
.br
.ti -1c
.RI "(id) - \fBinitWithSysFilePath:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBmediaPath\fP"
.br
.ti -1c
.RI "(NSString *) - \fBthumbnailPath\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NSString * \fBdbpath\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "- (id) initWithSysFilePath: (NSString *)path"

.PP
Reimplemented from \fBWSQNews\fP\&.
.SS "- (\fBNewsObjectPhoto\fP *) loadPhoto "

.SS "- (NSString *) mediaPath "

.SS "- (NSString *) thumbnailPath "

.SH "Property Documentation"
.PP 
.SS "- (NSString*) dbpath\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
