.TH "<NewsLoaderDelegate>" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
<NewsLoaderDelegate> \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <NewsLoader\&.h>\fP
.PP
Inherited by \fBBWNewsWriter\fP, \fBBWPhotoVideoViewController\fP, \fBDetailViewController\fP, and \fBMasterViewController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(void) - \fBnewsLoaderDidLoadNewsList\fP"
.br
.ti -1c
.RI "(void) - \fBnewsLoaderDidLoadFile\fP"
.br
.ti -1c
.RI "(void) - \fBnoChange\fP"
.br
.ti -1c
.RI "(void) - \fBsaveNewsObjectSucceed\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (void) newsLoaderDidLoadFile "

.SS "- (void) newsLoaderDidLoadNewsList "

.SS "- (void) noChange "

.SS "- (void) saveNewsObjectSucceed "


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
