.TH "socioville/Libraries/CustomSegue/NoAnimPushSegue.m" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socioville/Libraries/CustomSegue/NoAnimPushSegue.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'NoAnimPushSegue\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
