.TH "NSDictionary(Dropbox)" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NSDictionary(Dropbox) \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <NSDictionary+Dropbox\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(NSString *) - \fBurlRepresentation\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "(NSDictionary *) + \fBdictionaryWithQueryString:\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "+ (NSDictionary *) dictionaryWithQueryString: (NSString *)query"

.SS "- (NSString *) urlRepresentation "


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
