.TH "NSObject(SBProxyForJson)" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NSObject(SBProxyForJson) \- 
.PP
Allows generation of JSON for otherwise unsupported classes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#import <DBJsonWriter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(id) - \fBproxyForJson\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Allows generation of JSON for otherwise unsupported classes\&. 

If you have a custom class that you want to create a JSON representation for you can implement this method in your class\&. It should return a representation of your object defined in terms of objects that can be translated into JSON\&. For example, a Person object might implement it like this:
.PP
.PP
.nf
- (id)jsonProxyObject {
   return [NSDictionary dictionaryWithObjectsAndKeys:
       name, @'name',
       phone, @'phone',
       email, @'email',
       nil];
}
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "- (id) proxyForJson "


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
