.TH "NSString(Dropbox)" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NSString(Dropbox) \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <NSString+Dropbox\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(NSString *) - \fBnormalizedDropboxPath\fP"
.br
.ti -1c
.RI "(BOOL) - \fBisEqualToDropboxPath:\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (BOOL) isEqualToDropboxPath: (NSString *)otherPath"

.SS "- (NSString*) normalizedDropboxPath "


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
