.TH "DropboxSDK.framework/Headers/NSString+DBJSON.h" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DropboxSDK.framework/Headers/NSString+DBJSON.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <Foundation/Foundation\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "category \fBNSString(NSString_DBJSON)\fP"
.br
.RI "\fIAdds JSON parsing methods to NSString\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
