.TH "NSURL(MPURLParameterAdditions)" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NSURL(MPURLParameterAdditions) \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <NSURL+MPURLParameterAdditions\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(NSURL *) - \fBurlByAddingParameters:\fP"
.br
.ti -1c
.RI "(NSURL *) - \fBurlByAddingParameterDictionary:\fP"
.br
.ti -1c
.RI "(NSURL *) - \fBurlByRemovingQuery\fP"
.br
.ti -1c
.RI "(NSString *) - \fBabsoluteNormalizedString\fP"
.br
.ti -1c
.RI "(BOOL) - \fBdomainMatches:\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (NSString *) absoluteNormalizedString "

.SS "- (BOOL) domainMatches: (NSString *)inString"

.SS "- (NSURL *) urlByAddingParameterDictionary: (NSDictionary *)inParameters"

.SS "- (NSURL *) urlByAddingParameters: (NSArray *)inParameters"

.SS "- (NSURL *) urlByRemovingQuery "


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
