.TH "NSURL(MPURLEscapingAdditions)" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NSURL(MPURLEscapingAdditions) \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <NSString+URLEscapingAdditions\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(NSString *) - \fBstringByAddingURIPercentEscapesUsingEncoding:\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (NSString *) stringByAddingURIPercentEscapesUsingEncoding: (NSStringEncoding)inEncoding"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
