.TH "ProgressBanner" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProgressBanner \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <ProgressBanner\&.h>\fP
.SS "Properties"

.in +1c
.ti -1c
.RI "UILabel * \fBstatusLable\fP"
.br
.ti -1c
.RI "UIActivityIndicatorView * \fBlittleWheel\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "- (UIActivityIndicatorView*) littleWheel\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"

.SS "- (UILabel*) statusLable\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
