.TH "socioville/PullRefreshTableViewController.m" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socioville/PullRefreshTableViewController.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import <QuartzCore/QuartzCore\&.h>\fP
.br
\fC#import 'PullRefreshTableViewController\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBREFRESH_HEADER_HEIGHT\fP   52\&.0f"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define REFRESH_HEADER_HEIGHT   52\&.0f"

.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
