.TH "PullRefreshTableViewController" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PullRefreshTableViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PullRefreshTableViewController\&.h>\fP
.PP
Inherited by \fBMasterViewController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(void) - \fBsetupStrings\fP"
.br
.ti -1c
.RI "(void) - \fBaddPullToRefreshHeader\fP"
.br
.ti -1c
.RI "(void) - \fBstartLoading\fP"
.br
.ti -1c
.RI "(void) - \fBstopLoading\fP"
.br
.ti -1c
.RI "(void) - \fBrefresh\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "BOOL \fBisDragging\fP"
.br
.ti -1c
.RI "BOOL \fBisLoading\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "UIView * \fBrefreshHeaderView\fP"
.br
.ti -1c
.RI "UILabel * \fBrefreshLabel\fP"
.br
.ti -1c
.RI "UIImageView * \fBrefreshArrow\fP"
.br
.ti -1c
.RI "UIActivityIndicatorView * \fBrefreshSpinner\fP"
.br
.ti -1c
.RI "NSString * \fBtextPull\fP"
.br
.ti -1c
.RI "NSString * \fBtextRelease\fP"
.br
.ti -1c
.RI "NSString * \fBtextLoading\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (void) addPullToRefreshHeader "

.SS "- (void) refresh "

.SS "- (void) setupStrings "

.SS "- (void) startLoading "

.SS "- (void) stopLoading "

.SH "Member Data Documentation"
.PP 
.SS "- (BOOL) isDragging\fC [protected]\fP"

.SS "- (BOOL) isLoading\fC [protected]\fP"

.SH "Property Documentation"
.PP 
.SS "- (UIImageView *) refreshArrow\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"

.SS "- (UIView *) refreshHeaderView\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"

.SS "- (UILabel *) refreshLabel\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"

.SS "- (UIActivityIndicatorView *) refreshSpinner\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"

.SS "- (NSString *) textLoading\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [copy]\fP"

.SS "- (NSString *) textPull\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [copy]\fP"

.SS "- (NSString *) textRelease\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [copy]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
