.TH "RCSwitchOnOff" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCSwitchOnOff \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <RCSwitchOnOff\&.h>\fP
.PP
Inherits \fBRCSwitch\fP\&.
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "UILabel * \fBonText\fP"
.br
.ti -1c
.RI "UILabel * \fBoffText\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Data Documentation"
.PP 
.SS "- (UILabel*) offText\fC [protected]\fP"

.SS "- (UILabel*) onText\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
