.TH "socioville/Libraries/RCSwitch/RCSwitch.m" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socioville/Libraries/RCSwitch/RCSwitch.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'RCSwitch\&.h'\fP
.br
\fC#import <QuartzCore/QuartzCore\&.h>\fP
.br
\fC#import 'BWAppDelegate\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "category \fBRCSwitch()\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
