.TH "RCSwitch()" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCSwitch() \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(void) - \fBregenerateImages\fP"
.br
.ti -1c
.RI "(void) - \fBperformSwitchToPercent:\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (void) performSwitchToPercent: (float)toPercent"

.SS "- (void) regenerateImages "


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
