.TH "socioville/Libraries/SampleSegment.m" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socioville/Libraries/SampleSegment.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'SampleSegment\&.h'\fP
.br
\fC#import 'BWAppDelegate\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "category \fBSampleSegment()\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBUTTON_WIDTH\fP   155\&.0"
.br
.ti -1c
.RI "#define \fBBUTTON_SEGMENT_WIDTH\fP   155\&.0"
.br
.ti -1c
.RI "#define \fBCAP_WIDTH\fP   12\&.0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUTTON_SEGMENT_WIDTH   155\&.0"

.SS "#define BUTTON_WIDTH   155\&.0"

.SS "#define CAP_WIDTH   12\&.0"

.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
