.TH "SampleSegment" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SampleSegment \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <SampleSegment\&.h>\fP
.PP
Inherits \fB<CustomSegmentedControlDelegate>\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "NSArray * \fBtitles\fP"
.br
.ti -1c
.RI "id< \fBSampleSegmentDelegate\fP > \fBdelegate\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Property Documentation"
.PP 
.SS "- (id<\fBSampleSegmentDelegate\fP>) delegate\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (NSArray*) titles\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
