.TH "SampleSegment()" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SampleSegment() \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(UIButton *) - \fBbuttonForIndex:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBCustomSegmentedControl\fP * \fBsegments\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (UIButton *) buttonForIndex: (NSUInteger)segmentIndex"

.SH "Property Documentation"
.PP 
.SS "- (\fBCustomSegmentedControl\fP*) segments\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
