.TH "STSegmentedControl(Private)" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STSegmentedControl(Private) \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(void) - \fBupdateUI\fP"
.br
.ti -1c
.RI "(void) - \fBdeselectAllSegments\fP"
.br
.ti -1c
.RI "(void) - \fBinsertSegmentWithObject:atIndex:\fP"
.br
.ti -1c
.RI "(void) - \fBsetObject:forSegmentAtIndex:\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (void) deselectAllSegments "

.SS "- (void) insertSegmentWithObject: (NSObject *)object(NSUInteger)index"

.SS "- (void) setObject: (NSObject *)object(NSUInteger)index"

.SS "- (void) updateUI "


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
