.TH "UIAlertView(Dropbox)" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIAlertView(Dropbox) \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <UIAlertView+Dropbox\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "(void) + \fBshowAlertWithTitle:message:delegate:cancelButtonTitle:otherButtonTitles:\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "+ (void) showAlertWithTitle: (NSString *)title(NSString *)message(id< UIAlertViewDelegate >)delegate(NSString *)cancelButtonTitle(NSString *)otherButtonTitlesNS_REQUIRES_NIL_TERMINATION"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
