.TH "UIElementsViewController" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIElementsViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <UIElementsViewController\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(IBAction) - \fBsliderValueChanged:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IBOutlet UIScrollView * \fBscrollView\fP"
.br
.ti -1c
.RI "IBOutlet UIButton * \fBcolorButton\fP"
.br
.ti -1c
.RI "IBOutlet UIButton * \fBcolorButtonSelected\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (IBAction) sliderValueChanged: (id)sender"

.SH "Property Documentation"
.PP 
.SS "- (IBOutlet UIButton*) colorButton\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"

.SS "- (IBOutlet UIButton*) colorButtonSelected\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"

.SS "- (IBOutlet UIScrollView*) scrollView\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
