.TH "UIElementsViewController()" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIElementsViewController() \- 
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBADVPopoverProgressBar\fP * \fBprogressBar\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "- (\fBADVPopoverProgressBar\fP*) progressBar\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [strong]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
