.TH "Yini/UIPullToReloadHeaderView.m" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Yini/UIPullToReloadHeaderView.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import <QuartzCore/QuartzCore\&.h>\fP
.br
\fC#import 'UIPullToReloadHeaderView\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "category \fBUIPullToReloadHeaderView()\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTEXT_COLOR\fP   [UIColor colorWithRed:117\&.0/255\&.0 green:138\&.0/255\&.0 blue:167\&.0/255\&.0 alpha:1\&.0]"
.br
.ti -1c
.RI "#define \fBBORDER_COLOR\fP   [UIColor colorWithRed:113\&.0/255\&.0 green:120\&.0/255\&.0 blue:128\&.0/255\&.0 alpha:1\&.0]"
.br
.ti -1c
.RI "#define \fBBACKGROUND_COLOR\fP   [UIColor colorWithRed:226\&.0/255\&.0 green:231\&.0/255\&.0 blue:237\&.0/255\&.0 alpha:1\&.0];"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BACKGROUND_COLOR   [UIColor colorWithRed:226\&.0/255\&.0 green:231\&.0/255\&.0 blue:237\&.0/255\&.0 alpha:1\&.0];"

.SS "#define BORDER_COLOR   [UIColor colorWithRed:113\&.0/255\&.0 green:120\&.0/255\&.0 blue:128\&.0/255\&.0 alpha:1\&.0]"

.SS "#define TEXT_COLOR   [UIColor colorWithRed:117\&.0/255\&.0 green:138\&.0/255\&.0 blue:167\&.0/255\&.0 alpha:1\&.0]"

.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
