.TH "UIPullToReloadHeaderView" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIPullToReloadHeaderView \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <UIPullToReloadHeaderView\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(void) - \fBsetStatus:animated:\fP"
.br
.ti -1c
.RI "(void) - \fBstartReloading:animated:\fP"
.br
.ti -1c
.RI "(void) - \fBfinishReloading:animated:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NSDate * \fBlastUpdatedDate\fP"
.br
.ti -1c
.RI "\fBUIPullToReloadStatus\fP \fBstatus\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (void) finishReloading: (UITableView *)tableView(BOOL)animated"

.SS "- (void) setStatus: (\fBUIPullToReloadStatus\fP)status(BOOL)animated"

.SS "- (void) startReloading: (UITableView *)tableView(BOOL)animated"

.SH "Property Documentation"
.PP 
.SS "- (NSDate *) lastUpdatedDate\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"

.SS "- (\fBUIPullToReloadStatus\fP) status\fC [read]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
