.TH "socioville/Libraries/Categories/UISearchBar/UISearchBar+TextColor.m" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socioville/Libraries/Categories/UISearchBar/UISearchBar+TextColor.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'UISearchBar+TextColor\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
