.TH "UISearchBar(TextColor)" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UISearchBar(TextColor) \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <UISearchBar+TextColor\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(UITextField *) - \fBfield\fP"
.br
.ti -1c
.RI "(UIColor *) - \fBtextColor\fP"
.br
.ti -1c
.RI "(void) - \fBsetTextColor:\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (UITextField *) field "

.SS "- (void) setTextColor: (UIColor *)color"

.SS "- (UIColor *) textColor "


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
