.TH "<WSQFileHelperDelegate>" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
<WSQFileHelperDelegate> \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <WSQFileHelper\&.h>\fP
.PP
Inherited by \fBMenuViewController\fP, and \fBNewsLoader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(void) - \fBloadedFile\fP"
.br
.ti -1c
.RI "(void) - \fBnoChange\fP"
.br
.ti -1c
.RI "(void) - \fBloadedNewsList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "- (void) loadedFile "

.SS "- (void) loadedNewsList \fC [optional]\fP"

.SS "- (void) noChange \fC [optional]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
