.TH "<WSQFileUploaderDelegate>" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
<WSQFileUploaderDelegate> \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <WSQFileUploader\&.h>\fP
.PP
Inherited by \fBBWMyLordActivityWriter\fP, \fBBWMyLordInfoViewController\fP, \fBBWNewsWriter\fP, and \fBNewsLoader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(void) - \fBfileUploadFinished:\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (void) fileUploadFinished: (BOOL)isSucceed\fC [optional]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
