.TH "Yini/WSQNews.h" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Yini/WSQNews.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <Foundation/Foundation\&.h>\fP
.br
\fC#import <DropboxSDK/DropboxSDK\&.h>\fP
.br
\fC#import 'WSQFileHelper\&.h'\fP
.br
\fC#import 'BWComment\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWSQNews\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBWSQNewsTypes\fP { \fBWSQPhoto\fP, \fBWSQVideo\fP, \fBWSQArticle\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBWSQNewsTypes\fP"

.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIWSQPhoto \fP\fP
.TP
\fB\fIWSQVideo \fP\fP
.TP
\fB\fIWSQArticle \fP\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
