.TH "ZUUIRevealController()" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZUUIRevealController() \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(CGFloat) - \fB_calculateOffsetForTranslationInView:\fP"
.br
.ti -1c
.RI "(void) - \fB_revealAnimation\fP"
.br
.ti -1c
.RI "(void) - \fB_concealAnimation\fP"
.br
.ti -1c
.RI "(void) - \fB_addFrontViewControllerToHierarchy:\fP"
.br
.ti -1c
.RI "(void) - \fB_addRearViewControllerToHierarchy:\fP"
.br
.ti -1c
.RI "(void) - \fB_removeViewControllerFromHierarchy:\fP"
.br
.ti -1c
.RI "(void) - \fB_swapCurrentFrontViewControllerWith:animated:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "UIView * \fBfrontView\fP"
.br
.ti -1c
.RI "UIView * \fBrearView\fP"
.br
.ti -1c
.RI "float \fBpreviousPanOffset\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (void) _addFrontViewControllerToHierarchy: (UIViewController *)frontViewController"

.SS "- (void) _addRearViewControllerToHierarchy: (UIViewController *)rearViewController"

.SS "- (CGFloat) _calculateOffsetForTranslationInView: (CGFloat)x"

.SS "- (void) _concealAnimation "

.SS "- (void) _removeViewControllerFromHierarchy: (UIViewController *)frontViewController"

.SS "- (void) _revealAnimation "

.SS "- (void) _swapCurrentFrontViewControllerWith: (UIViewController *)newFrontViewController(BOOL)animated"

.SH "Property Documentation"
.PP 
.SS "- (UIView*) frontView\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"

.SS "- (float) previousPanOffset\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"

.SS "- (UIView*) rearView\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [retain]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
