.TH "socioville/Libraries/ZUUIRevealController/ZUUIRevealController.m" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socioville/Libraries/ZUUIRevealController/ZUUIRevealController.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import <QuartzCore/QuartzCore\&.h>\fP
.br
\fC#import 'ZUUIRevealController\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "category \fBZUUIRevealController()\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBREVEAL_EDGE\fP   260\&.0f"
.br
.ti -1c
.RI "#define \fBREVEAL_EDGE_OVERDRAW\fP   60\&.0f"
.br
.ti -1c
.RI "#define \fBREVEAL_VIEW_TRIGGER_LEVEL_LEFT\fP   125\&.0f"
.br
.ti -1c
.RI "#define \fBREVEAL_VIEW_TRIGGER_LEVEL_RIGHT\fP   200\&.0f"
.br
.ti -1c
.RI "#define \fBVELOCITY_REQUIRED_FOR_QUICK_FLICK\fP   1300\&.0f"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define REVEAL_EDGE   260\&.0f"

.SS "#define REVEAL_EDGE_OVERDRAW   60\&.0f"

.SS "#define REVEAL_VIEW_TRIGGER_LEVEL_LEFT   125\&.0f"

.SS "#define REVEAL_VIEW_TRIGGER_LEVEL_RIGHT   200\&.0f"

.SS "#define VELOCITY_REQUIRED_FOR_QUICK_FLICK   1300\&.0f"

.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
