.TH "socioville/Libraries/ZUUIRevealController/ZUUIRevealController.h" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socioville/Libraries/ZUUIRevealController/ZUUIRevealController.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <UIKit/UIKit\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBZUUIRevealController\fP"
.br
.ti -1c
.RI "protocol \fB<ZUUIRevealControllerDelegate>\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBFrontViewPosition\fP { \fBFrontViewPositionLeft\fP, \fBFrontViewPositionRight\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBFrontViewPosition\fP"

.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIFrontViewPositionLeft \fP\fP
.TP
\fB\fIFrontViewPositionRight \fP\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
