.TH "<ZUUIRevealControllerDelegate>" 3 "Thu Aug 9 2012" "Version 1.0" "Yini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
<ZUUIRevealControllerDelegate> \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <ZUUIRevealController\&.h>\fP
.PP
Inherited by \fBMasterViewController\fP, and \fBMenuViewController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(BOOL) - \fBrevealController:shouldRevealRearViewController:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBrevealController:shouldHideRearViewController:\fP"
.br
.ti -1c
.RI "(void) - \fBrevealController:willRevealRearViewController:\fP"
.br
.ti -1c
.RI "(void) - \fBrevealController:didRevealRearViewController:\fP"
.br
.ti -1c
.RI "(void) - \fBrevealController:willHideRearViewController:\fP"
.br
.ti -1c
.RI "(void) - \fBrevealController:didHideRearViewController:\fP"
.br
.ti -1c
.RI "(void) - \fBrevealController:willSwapToFrontViewController:\fP"
.br
.ti -1c
.RI "(void) - \fBrevealController:didSwapToFrontViewController:\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (void) revealController: (\fBZUUIRevealController\fP *)revealController(UIViewController *)rearViewController\fC [optional]\fP"

.SS "- (void) revealController: (\fBZUUIRevealController\fP *)revealController(UIViewController *)rearViewController\fC [optional]\fP"

.SS "- (void) revealController: (\fBZUUIRevealController\fP *)revealController(UIViewController *)frontViewController\fC [optional]\fP"

.SS "- (BOOL) revealController: (\fBZUUIRevealController\fP *)revealController(UIViewController *)rearViewController\fC [optional]\fP"

.SS "- (BOOL) revealController: (\fBZUUIRevealController\fP *)revealController(UIViewController *)rearViewController\fC [optional]\fP"

.SS "- (void) revealController: (\fBZUUIRevealController\fP *)revealController(UIViewController *)rearViewController\fC [optional]\fP"

.SS "- (void) revealController: (\fBZUUIRevealController\fP *)revealController(UIViewController *)rearViewController\fC [optional]\fP"

.SS "- (void) revealController: (\fBZUUIRevealController\fP *)revealController(UIViewController *)frontViewController\fC [optional]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Yini from the source code\&.
